name: Clean dist folder

on:
  workflow_dispatch:
jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: delete files
        run: find docs/* ! -name 'CNAME' -type f -exec rm -rf {} + && find docs/* ! -name 'CNAME' -type d -exec rm -rf {} +
      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
